### ISSUE TITLE
Some user's songs result in Uncaught InvalidStateError and will not play.

### ISSUE THREAD

**Issue by bigtunacan** [ajacksified/song-of-github#31]
Uncaught InvalidStateError: Failed to execute 'start' on 'AudioBufferSourceNode': Start time must be a finite non-negative number: -0.088

Examples here

http://song-of-github.herokuapp.com/?username=getify

and here

http://song-of-github.herokuapp.com/?username=bf4

Tested on Firefox/Chrome/Safari.  Same error on all three.

**Comment by ssorallen** [comment]
I ran into this as well and discovered it's dependent on how long it takes the audio API to initialize. I will send a PR with a fix.
