### ISSUE TITLE
No indicator when no commits

### ISSUE THREAD

**Issue by Haroenv** [ajacksified/song-of-github#34]
You can't keep track of how far in the song you are, when you are in an area with a lot of whitespace.

Solution could be to show those that passed with a light overlay.

**Comment by lmatiolis** [comment]
:+1: for some kind of playback indication...

**Comment by ajacksified** [comment]
> Solution could be to show those that passed with a light overlay.

The solution is to commit more open source ;)

**Comment by Haroenv** [comment]
Haha, good solution :)

Haroen
