### ISSUE TITLE
Music does not play for my activity

### ISSUE THREAD

**Issue by alvarocavalcanti** [ajacksified/song-of-github#35]
Hey there. I've tried my username a few times and it won't play anything. I've tried with other usernames and it works, in the same browser session. Tried in both Chrome and FireFox, also alongside another username and no song for both. :(

https://song-of-github.herokuapp.com/?username=alvarocavalcanti

**Comment by alvarocavalcanti** [comment]
Found this another one that does not work:

https://song-of-github.herokuapp.com/?username=mauriciomelo

**Comment by ssorallen** [comment]
This is due to a bug that was fixed in pull request #32.

@ajacksified, was the prod site on Heroku redeployed with that fix? It should solve @alvarocavalcanti's issue and issue #33.

**Comment by alvarocavalcanti** [comment]
Thanks! :)

**Comment by ajacksified** [comment]
It was:

```
ajacksified@jack.local:~/projects/song-of-github [master]
[07:32:27] $ git pull
Already up-to-date.

ajacksified@jack.local:~/projects/song-of-github [master]
[07:32:32] $ git push heroku master
Everything up-to-date
```

Weird thing is... now it works for those users. vOv

**Comment by ssorallen** [comment]
Strange... works for me now too. :tada:
